import { Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const styles = {
  appContainer: {
    flex: 1,
    backgroundColor: "#f9fafb",
  },
  container: {
    flex: 1,
    height: "100vh",
  },
  header: {
    backgroundColor: "#fff",
    padding: 16,
    paddingTop: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
  },
  viewButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    minWidth: 40,
    alignItems: "center",
  },
  viewButtonActive: {
    backgroundColor: "#3b82f6",
  },
  viewButtonText: {
    fontSize: 20,
    color: "#111827",
  },
  backButton: {
    fontSize: 16,
    color: "#3b82f6",
  },
  searchContainer: {
    backgroundColor: "#fff",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  searchIcon: {
    position: "absolute",
    left: 28,
    zIndex: 1,
    fontSize: 20,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 40,
    paddingVertical: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  content: {
    flex: 1,
    height: "100%",
  },
  loadingText: {
    textAlign: "center",
    marginTop: 40,
    fontSize: 16,
    color: "#6b7280",
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 8,
  },
  gridItem: {
    width: (width - 32) / 2,
    backgroundColor: "#fff",
    margin: 4,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  gridImage: {
    width: "100%",
    height: 150,
    resizeMode: "contain",
    backgroundColor: "#f9fafb",
  },
  listContainer: {
    padding: 8,
  },
  listItem: {
    backgroundColor: "#fff",
    marginBottom: 8,
    borderRadius: 12,
    overflow: "hidden",
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  listImage: {
    width: 100,
    height: 100,
    resizeMode: "contain",
    backgroundColor: "#f9fafb",
  },
  productInfo: {
    padding: 12,
    flex: 1,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#3b82f6",
    marginBottom: 4,
  },
  productCategory: {
    fontSize: 12,
    color: "#6b7280",
    textTransform: "capitalize",
  },
  detailImage: {
    width: "100%",
    height: 300,
    resizeMode: "contain",
    backgroundColor: "#fff",
  },
  detailContent: {
    padding: 16,
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  detailPrice: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#595c60ff",
    marginBottom: 8,
  },
  balance: {
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    backgroundColor: "#dadadaff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  detailCategory: {
    fontSize: 14,
    color: "#6b7280",
    textTransform: "capitalize",
    marginBottom: 16,
  },
  detailDescription: {
    fontSize: 16,
    color: "#4b5563",
    lineHeight: 24,
    marginBottom: 24,
  },
  detailActions: {
    flexDirection: "row",
    gap: 12,
  },
  buyButton: {
    flex: 1,
    backgroundColor: "#595e65ff",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buyButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  sellButton: {
    flex: 1,
    backgroundColor: "#10b981",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  sellButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    marginTop: 60,
  },
  emptyIcon: {
    fontSize: 64,
  },
  emptyText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#6b7280",
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#9ca3af",
    marginTop: 8,
  },
  myProductItem: {
    backgroundColor: "#fff",
    marginBottom: 8,
    borderRadius: 12,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  myProductInfo: {
    padding: 12,
    flex: 1,
  },
  removeButton: {
    padding: 12,
  },
  removeButtonText: {
    fontSize: 24,
    color: "#ef4444",
  },
  cartItem: {
    backgroundColor: "#fff",
    marginBottom: 8,
    borderRadius: 12,
    overflow: "hidden",
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
  },
  cartImage: {
    width: 80,
    height: 80,
    resizeMode: "contain",
    backgroundColor: "#f9fafb",
    borderRadius: 8,
  },
  cartInfo: {
    flex: 1,
    marginLeft: 12,
  },
  cartTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  cartPrice: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 4,
  },
  cartTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#3b82f6",
  },
  cartTotalContainer: {
    backgroundColor: "#fff",
    padding: 16,
    marginTop: 16,
    marginHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: "#6b7280",
  },
  totalAmount: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#3b82f6",
    marginTop: 4,
  },
  checkoutButton: {
    backgroundColor: "#10b981",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
    marginBottom: 16,
    marginHorizontal: 8,
  },
  checkoutButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  navbar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingBottom: 20,
    paddingTop: 8,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    position: "relative",
  },
  navIcon: {
    fontSize: 24,
  },
  navIconActive: {
    transform: [{scale: 1.2}],
  },
  navText: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 4,
  },
  navTextActive: {
    color: "#3b82f6",
    fontWeight: "600",
  },
  badge: {
    position: "absolute",
    top: 0,
    right: "30%",
    backgroundColor: "#ef4444",
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },
  gameCard: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 32,
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  gameCardIcon: {
    fontSize: 48,
  },
  gameCardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    marginTop: 16,
  },
  gameCardDescription: {
    fontSize: 14,
    color: "#6b7280",
    marginTop: 8,
  },
  gameContainer: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  gameTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111827",
    textAlign: "center",
    marginBottom: 16,
  },
  gameMessage: {
    fontSize: 16,
    color: "#4b5563",
    textAlign: "center",
    marginBottom: 12,
  },
  gameAttempts: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 20,
  },
  gameInput: {
    backgroundColor: "#f3f4f6",
    padding: 16,
    borderRadius: 12,
    fontSize: 18,
    textAlign: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  gameButton: {
    backgroundColor: "#3b82f6",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  gameButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  memoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginVertical: 20,
  },
  memoryCard: {
    width: 70,
    height: 70,
    backgroundColor: "#3b82f6",
    margin: 4,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  memoryCardFlipped: {
    backgroundColor: "#10b981",
  },
  memoryCardText: {
    fontSize: 32,
  },
  winMessage: {
    alignItems: "center",
    padding: 16,
    backgroundColor: "#d1fae5",
    borderRadius: 12,
    marginVertical: 16,
  },
  winText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#059669",
  },
};

export default styles;